# Generated by Django 3.2.9 on 2022-04-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='', null=True, upload_to='pdf/'),
        ),
    ]
