# Generated by Django 3.2.9 on 2022-04-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
