# Generated by Django 3.2.9 on 2022-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20220403_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='follow_author',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, default=False, max_length=2083),
        ),
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ImageField(blank=True, default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdf/'),
        ),
    ]
