# Generated by Django 3.2.9 on 2022-04-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20220403_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdfurl',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
