# Generated by Django 3.2.9 on 2022-05-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20220516_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None)),
                ('title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
