# Generated by Django 3.2.9 on 2022-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20220516_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.IntegerField(),
        ),
    ]
