# Generated by Django 3.2.9 on 2022-05-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
