# Generated by Django 3.2.9 on 2022-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20220522_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category3',
        ),
    ]
