# Generated by Django 3.2.9 on 2022-05-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_remove_book_category3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category3',
        ),
    ]
