# Generated by Django 3.2.9 on 2022-05-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_delete_category3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category2',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
