# Generated by Django 3.2.9 on 2022-05-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_auto_20220522_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category2'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.category1'),
        ),
    ]
