# Generated by Django 3.2.9 on 2022-05-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_book_seoclicks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Click',
        ),
    ]
